// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class Address
    {
        public long AddressId { get; set; }
        [StringLength(15)]
        public string NumberName { get; set; }
        [StringLength(63)]
        public string Street { get; set; }
        [StringLength(63)]
        public string Street2 { get; set; }
        [StringLength(63)]
        public string Street3 { get; set; }
        [StringLength(31)]
        public string TownCity { get; set; }
        [StringLength(31)]
        public string County { get; set; }
        public short CountryId { get; set; }
        [StringLength(10)]
        public string PostCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public int? CompanyId { get; set; }
        public int? ProjectId { get; set; }

        [ForeignKey("CompanyId")]
        [InverseProperty("Addresses")]
        public virtual Company Company { get; set; }
        [ForeignKey("CountryId")]
        [InverseProperty("Addresses")]
        public virtual Country Country { get; set; }
        [ForeignKey("ProjectId")]
        [InverseProperty("Addresses")]
        public virtual Project Project { get; set; }
    }
}