// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class AspNetUserToken
    {
        [StringLength(150)]
        public string UserId { get; set; }
        [StringLength(150)]
        public string LoginProvider { get; set; }
        [StringLength(150)]
        public string Name { get; set; }
        public string Value { get; set; }
    }
}