// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class AzureCompanyResourceUrl
    {
        public long AzureCompanyResourceUrlId { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        [Column("URL")]
        [StringLength(511)]
        public string Url { get; set; }
        [Required]
        [StringLength(511)]
        public string Key { get; set; }
        [Required]
        [StringLength(63)]
        public string ResourceType { get; set; }
        public int CompanyId { get; set; }

        [ForeignKey("CompanyId")]
        [InverseProperty("AzureCompanyResourceUrls")]
        public virtual Company Company { get; set; }
    }
}