// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class BlockPosition
    {
        public BlockPosition()
        {
            ProfileAttributes = new HashSet<ProfileAttribute>();
        }

        public byte BlockPositionId { get; set; }
        [Required]
        [StringLength(15)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? UserId { get; set; }

        [InverseProperty("BlockPosition")]
        public virtual ICollection<ProfileAttribute> ProfileAttributes { get; set; }
    }
}