// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class Country
    {
        public Country()
        {
            Addresses = new HashSet<Address>();
        }

        public short CountryId { get; set; }
        [Required]
        [Column("ISO")]
        [StringLength(3)]
        public string Iso { get; set; }
        [Required]
        [StringLength(127)]
        public string Name { get; set; }
        [Required]
        [StringLength(127)]
        public string SentenceCaseName { get; set; }
        [Column("ISO3")]
        [StringLength(3)]
        public string Iso3 { get; set; }
        [Column("numcode")]
        public short? Numcode { get; set; }
        [Column("phonecode")]
        public int Phonecode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? UserId { get; set; }

        [InverseProperty("Country")]
        public virtual ICollection<Address> Addresses { get; set; }
    }
}