// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class Currency
    {
        public short CurrencyId { get; set; }
        [Required]
        [StringLength(100)]
        public string Entity { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(3)]
        public string AlphabeticCode { get; set; }
        [StringLength(3)]
        public string NumericCode { get; set; }
        [StringLength(1)]
        public string MinorUnit { get; set; }
        public bool IsFundYesNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? UserId { get; set; }
    }
}