// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class DocumentLayer
    {
        public long DocumentLayerId { get; set; }
        [Required]
        [StringLength(1023)]
        public string Name { get; set; }
        public long DocumentId { get; set; }

        [ForeignKey("DocumentId")]
        [InverseProperty("DocumentLayers")]
        public virtual Document Document { get; set; }
    }
}