// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class Document
    {
        public Document()
        {
            DocumentFeatures = new HashSet<DocumentFeature>();
            DocumentLayers = new HashSet<DocumentLayer>();
            DocumentTemplates = new HashSet<DocumentTemplate>();
            ImageGrids = new HashSet<ImageGrid>();
            Sentences = new HashSet<Sentence>();
            Tasks = new HashSet<Task>();
        }

        public long DocumentId { get; set; }
        [Required]
        [StringLength(1023)]
        public string FileName { get; set; }
        [Required]
        [StringLength(1023)]
        public string BlobUrl { get; set; }
        [Required]
        [StringLength(36)]
        public string ContainerName { get; set; }
        public bool Success { get; set; }
        public int ProjectId { get; set; }
        public int TemplateVersionId { get; set; }
        [Column(TypeName = "decimal(3, 2)")]
        public decimal? AzureConfidence { get; set; }
        [Column(TypeName = "decimal(3, 2)")]
        public decimal? GoogleConfidence { get; set; }
        [Column(TypeName = "decimal(3, 2)")]
        public decimal? AmazonConfidence { get; set; }
        public byte? PaperSizeId { get; set; }
        public byte PaperOrientationId { get; set; }
        public bool Processed { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        public string UserId { get; set; }
        [StringLength(7)]
        public string Type { get; set; }
        public byte[] File { get; set; }

        [ForeignKey("PaperOrientationId")]
        [InverseProperty("Documents")]
        public virtual PaperOrientation PaperOrientation { get; set; }
        [ForeignKey("PaperSizeId")]
        [InverseProperty("Documents")]
        public virtual PaperSize PaperSize { get; set; }
        [ForeignKey("TemplateVersionId")]
        [InverseProperty("Documents")]
        public virtual TemplateVersion TemplateVersion { get; set; }
        [ForeignKey("ProjectId")]
        [InverseProperty("Documents")]
        public virtual Project Project { get; set; }
        [InverseProperty("Document")]
        public virtual ICollection<DocumentFeature> DocumentFeatures { get; set; }
        [InverseProperty("Document")]
        public virtual ICollection<DocumentLayer> DocumentLayers { get; set; }
        [InverseProperty("Document")]
        public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }
        [InverseProperty("Document")]
        public virtual ICollection<ImageGrid> ImageGrids { get; set; }
        [InverseProperty("Document")]
        public virtual ICollection<Sentence> Sentences { get; set; }
        [InverseProperty("Document")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}