// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class DocumentFeature
    {
        public long DocumentFeatureId { get; set; }
        [Required]
        [StringLength(255)]
        public string Vendor { get; set; }
        [Required]
        [StringLength(1023)]
        public string Value { get; set; }
        public long DocumentId { get; set; }
        public long? Left { get; set; }
        public long? Top { get; set; }
        public long? Width { get; set; }
        public long? Height { get; set; }
        public byte? Feature { get; set; }
        public long? Center { get; set; }

        [ForeignKey("DocumentId")]
        [InverseProperty("DocumentFeatures")]
        public virtual Document Document { get; set; }
    }
}