// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class DrawingTemplate
    {
        public int DrawingTemplateId { get; set; }
        public long? DrawingId { get; set; }
        public int? ProfileVersionId { get; set; }

        [ForeignKey("DrawingId")]
        [InverseProperty("DrawingTemplates")]
        public virtual Drawing Drawing { get; set; }
        [ForeignKey("ProfileVersionId")]
        [InverseProperty("DrawingTemplates")]
        public virtual ProfileVersion ProfileVersion { get; set; }
    }
}