// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class DrawingLayer
    {
        public long DrawingLayerId { get; set; }
        [Required]
        [StringLength(1023)]
        public string Name { get; set; }
        public long DrawingId { get; set; }

        [ForeignKey("DrawingId")]
        [InverseProperty("DrawingLayers")]
        public virtual Drawing Drawing { get; set; }
    }
}