// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class Gender
    {
        public Gender()
        {
            AspNetUsers = new HashSet<AspNetUser>();
            Employees = new HashSet<Employee>();
        }

        public byte GenderId { get; set; }
        [Required]
        [StringLength(15)]
        public string Type { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        public string UserId { get; set; }

        [InverseProperty("Gender")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [InverseProperty("Gender")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}