// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class ImageGrid
    {
        public long ImageGridId { get; set; }
        [Required]
        public string Name { get; set; }
        public int WidthStart { get; set; }
        public int HeightStart { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        [Required]
        [Column("BlobURL")]
        [StringLength(2083)]
        public string BlobUrl { get; set; }
        public byte IterationAmazon { get; set; }
        public byte IterationAzure { get; set; }
        public byte IterationGoogle { get; set; }
        public bool ProcessedAmazon { get; set; }
        public bool ProcessedAzure { get; set; }
        public bool ProcessedGoogle { get; set; }
        public byte Type { get; set; }
        public long DrawingId { get; set; }

        [ForeignKey("DrawingId")]
        [InverseProperty("ImageGrids")]
        public virtual Drawing Drawing { get; set; }
    }
}