// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class PaperSize
    {
        public PaperSize()
        {
            Documents = new HashSet<Document>();
            ProfileAttributes = new HashSet<ProfileAttribute>();
        }

        public byte PaperSizeId { get; set; }
        [Required]
        [StringLength(31)]
        public string Name { get; set; }
        public int PixelWidth { get; set; }
        public int PixelHeight { get; set; }
        [Column(TypeName = "decimal(6, 1)")]
        public decimal? PhysicalWidth { get; set; }
        [Column(TypeName = "decimal(6, 1)")]
        public decimal? PhysicalHeight { get; set; }

        [InverseProperty("PaperSize")]
        public virtual ICollection<Document> Documents { get; set; }
        [InverseProperty("PaperSize")]
        public virtual ICollection<ProfileAttribute> ProfileAttributes { get; set; }
    }
}