// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class PaperOrientation
    {
        public PaperOrientation()
        {
            Documents = new HashSet<Document>();
        }

        public byte PaperOrientationId { get; set; }
        [Required]
        [StringLength(9)]
        public string Orientation { get; set; }

        [InverseProperty("PaperOrientation")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}