// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class Project
    {
        public Project()
        {
            Addresses = new HashSet<Address>();
            Documents = new HashSet<Document>();
        }

        public int ProjectId { get; set; }
        [Required]
        [StringLength(1024)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        public string StorageAccountName { get; set; }
        [Required]
        [StringLength(255)]
        public string StorageAccountKey { get; set; }
        public int CompanyId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        public long UserId { get; set; }

        [ForeignKey("CompanyId")]
        [InverseProperty("Projects")]
        public virtual Company Company { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<Address> Addresses { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}