// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class Property
    {
        public long PropertyId { get; set; }
        public Guid SentenceId { get; set; }
        public long TemplateAttributeId { get; set; }

        [ForeignKey("TemplateAttributeId")]
        [InverseProperty("Properties")]
        public virtual TemplateAttribute TemplateAttribute { get; set; }
        [ForeignKey("SentenceId")]
        [InverseProperty("Properties")]
        public virtual Sentence Sentence { get; set; }
    }
}