// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class StandardAttribute
    {
        public StandardAttribute()
        {
            ProfileAttributes = new HashSet<ProfileAttribute>();
        }

        public short StandardAttributeId { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        [InverseProperty("StandardAttribute")]
        public virtual ICollection<ProfileAttribute> ProfileAttributes { get; set; }
    }
}