// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class TemplateVersion
    {
        public TemplateVersion()
        {
            DocumentTemplates = new HashSet<DocumentTemplate>();
            Documents = new HashSet<Document>();
            TemplateAttributes = new HashSet<TemplateAttribute>();
        }

        public int TemplateVersionId { get; set; }
        [Required]
        [StringLength(1023)]
        public string Name { get; set; }
        public int CompanyId { get; set; }
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }
        public int? Width { get; set; }
        public int? Height { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? UserId { get; set; }
        public int? WidthOriginal { get; set; }
        public int? HeightOriginal { get; set; }
        public int? X { get; set; }
        public int? Y { get; set; }

        [ForeignKey("CompanyId")]
        [InverseProperty("TemplateVersions")]
        public virtual Company Company { get; set; }
        [InverseProperty("TemplateVersion")]
        public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }
        [InverseProperty("TemplateVersion")]
        public virtual ICollection<Document> Documents { get; set; }
        [InverseProperty("TemplateVersion")]
        public virtual ICollection<TemplateAttribute> TemplateAttributes { get; set; }
    }
}