// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    [Table("UserInfo")]
    public partial class UserInfo
    {
        [Key]
        public long UserInfoId { get; set; }
        [Required]
        [StringLength(63)]
        public string Value { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        public string Id { get; set; }
        public byte? UserInfoTypeId { get; set; }

        [ForeignKey("Id")]
        [InverseProperty("UserInfos")]
        public virtual AspNetUser IdNavigation { get; set; }
        [ForeignKey("UserInfoTypeId")]
        [InverseProperty("UserInfos")]
        public virtual UserInfoType UserInfoType { get; set; }
    }
}