// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class UserType
    {
        public UserType()
        {
            AspNetUsers = new HashSet<AspNetUser>();
        }

        public byte UserTypeId { get; set; }
        [Required]
        [StringLength(15)]
        public string Value { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }

        [InverseProperty("UserType")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}