// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataSummitDbModels
{
    public partial class UserInfoType
    {
        public UserInfoType()
        {
            UserInfos = new HashSet<UserInfo>();
        }

        public byte UserInfoTypeId { get; set; }
        [Required]
        [StringLength(63)]
        public string Type { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? UserId { get; set; }

        [InverseProperty("UserInfoType")]
        public virtual ICollection<UserInfo> UserInfos { get; set; }
    }
}